#version: '3.8'

services:
  #nextjs:
  #  build:
  #    context: ../roulettepopup
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4000:4000"  # コンテナのポート 4000 をホストのポート 4000 にマッピング
  #  volumes:
  #    - ../roulettepopup:/app  # ホストのディレクトリをコンテナにマウント
  #    - ../roulettepopup/.next:/app/.next  # ビルド済みの .next ディレクトリをマウント
  #  environment:
  #    - NEXT_PUBLIC_API_URL=http://localhost:3000/api  # Railsアプリケーションのポートを指定
  #  depends_on:
  #    - rails

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails db:seed && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"  # コンテナのポート 3000 をホストのポート 3000 にマッピング
    volumes:
      - .:/app
    environment:
      - DATABASE_DEV_USER=${DATABASE_DEV_USER}
      - DATABASE_DEV_PASSWORD=${DATABASE_DEV_PASSWORD}
      - DATABASE_URL=mysql2://${DATABASE_DEV_USER}:${DATABASE_DEV_PASSWORD}@db:3306/plusonedb_development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
