default: &default #アンカー
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["RDS_ENDPOINT"] %>
  port: 3306
  database: plusonedb_production
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  #socket: /tmp/mysql.sock

development:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_development

test:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_test

production:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_production
  #username: <%= ENV['DATABASE_DEV_USER'] %>
  #password: <%= ENV['DATABASE_DEV_PASSWORD'] %>