default: &default #アンカー
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["RDS_ENDPOINT"] %>
  port: 3306
  database: plusonedb_production
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  #socket: /tmp/mysql.sock

development:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_development

test:
  #<<: *default #エイリアス・ハッシュのマージ
  #database: plusonedb_test
  test:
  adapter:  mysql2
  encoding: utf8mb4
  host:     127.0.0.1     # もしくは localhost
  port:     3306
  username: <%= ENV.fetch('DATABASE_DEV_USER') %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  database: plusonedb_test
  pool: 5
  timeout: 5000

production:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_production
  #username: <%= ENV['DATABASE_DEV_USER'] %>
  #password: <%= ENV['DATABASE_DEV_PASSWORD'] %>