default: &default #アンカー
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: <%= ENV['DATABASE_DEV_HOST'] %>

development:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_development

test:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_test

production:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_production
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>