default: &default
  adapter: mysql2
  encoding: utf8mb4
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  database: plusonedb_development
  username: <%= ENV['DATABASE_DEV_USER'] || 'root' %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] || '' %>
  timeout: 5000

test:
  <<: *default
  host: <%= ENV['DATABASE_TEST_HOST'] || '127.0.0.1' %>
  database: plusonedb_test
  username: <%= ENV['DATABASE_TEST_USER'] || 'root' %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] || '' %>
  timeout: 5000

production:
  <<: *default
  host: <%= ENV['RDS_ENDPOINT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>