default: &default #アンカー
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["RDS_ENDPOINT"] %>
  port: 3306
  database: plusonedb_production
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  #socket: /tmp/mysql.sock

development:
  #<<: *default #エイリアス・ハッシュのマージ
  #database: plusonedb_development
  adapter:  mysql2
  encoding: utf8mb4
  host:     127.0.0.1     # もしくは localhost
  port:     3306
  username: <%= ENV['DATABASE_DEV_USER'] || 'root' %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] || '' %>
  database: plusonedb_development
  pool: 5
  timeout: 5000

test:
  adapter:  mysql2
  encoding: utf8mb4
  host: <%= ENV['DATABASE_TEST_HOST'] || 'mysql' %>
  port:     3306
  database: plusonedb_test
  username: <%= ENV['DATABASE_TEST_USER'] || 'root' %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] || '' %>
  pool: 5
  timeout: 5000

production:
  <<: *default #エイリアス・ハッシュのマージ
  database: plusonedb_production
  #username: <%= ENV['DATABASE_DEV_USER'] %>
  #password: <%= ENV['DATABASE_DEV_PASSWORD'] %>